name: fluentReports Renderer CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - name: Checkout Startup
        uses: actions/checkout@v2

      - name: Get Poppler
        run: sudo apt-get install poppler-utils

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm test

      - name: Upload Results
        uses: actions/upload-artifact@v1
        with:
          name: testresults
          path: /tmp/results.txt

      - name: Upload Res 2
        uses: actions/upload-artifact@v2
        with:
          name: images
          path: ~/work/fluentreports/fluentreports/examples/Check/